# Generated by Django 3.0.2 on 2020-02-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(height_field=100, upload_to=None, width_field=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
